/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'murillo.ivamoto' at '18/08/15 09:38' with Gradle 2.6
 *
 * @author murillo.ivamoto, @date 18/08/15 09:38
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
